groups:
- name: cluster-cpu-usage
  rules:

  - alert: high_cpu_usage
    expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[5m])) * 100)) > 85
    for: 5m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} under high cpu usage"
      description: "{{ $labels.instance }} is under high cpu usage for more than 5 minutes."
